# GitHub Pages config

title: TypeScript AMD
description: Basic implementation to run TypeScript AMD bundles.
author: Â© TypeScriptLibs and Contributors

email: bug@typescriptlibs.org
github_username:  typescriptlibs
rss: rss

github:
  private: true

header_pages:
  - SECURITY.md
  - LICENSE.md
  - www/all-libraries.md

include:
  - LICENSE.md
  - www/all-libraries.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-titles-from-headings

show_excerpts: false

theme: minima

minima:
  date_format: "%Y-%m-%d"
  skin: classic

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
